//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInstagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Image_Path { get; set; }
        public string Image_Type { get; set; }
        public string Image_Name { get; set; }
        public string Content { get; set; }
        public string Created { get; set; }
    
        public virtual User User { get; set; }
    }
}
